config/routes.rb
Rails.application.routes.draw do
  root to: "posts#index"
  resources :posts, only: [:index, :show, :destroy]
  get "posts/index" => "posts#index"
  get "new" => "posts#new"
  get "posts/:id" => "posts#show"
  get "about" => "pages#about"
  get "contact" => "pages#contact"
  post "posts/create" => "posts#create"
  devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @id = params[:id]
    @post = Post.find_by(id: params[:id])
  end

  def new
  end

  def create
    @post = Post.new(content: params[:content], user: current_user)

    if @post.save
      redirect_to posts_url
    else
      flash[:alert] = 'Error'
      redirect_to root_url
    end
  end

  def destroy
    @post = Post.find(params[:id])
      if @post.destroy
        redirect_to posts_url
      else
        flash[:alert] = 'Error'
        redirect_to root_url
      end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <title>Document</title>
  <head>
    <title>App</title>
      <meta charset="UTF-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width,initial-scale=1">
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>
      <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

      <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
      <%= javascript_importmap_tags %>
      <script src="https://cdn.tailwindcss.com"></script>
  </head>

  <body>
    <header>
      <nav class="relative flex w-full items-center justify-between mt-10 bg-blue-300">
      <div class="px-4">
        <%= link_to 'ホーム', root_path %>
      </div>
      <div class="text-sm px-8 gap-10 flex items-center">
        <%= link_to 'about', about_path%>
        <%= link_to 'contact', contact_path%>
        <button type="button" class="inline-block rounded animate-pulse bg-neutral-800 px-6 pb-2 pt-2.5 text-xs font-medium uppercase leading-normal text-neutral-50 shadow-[0_4px_9px_-4px_rgba(51,45,45,0.7)] transition duration-150 ease-in-out hover:bg-neutral-800 hover:shadow-[0_8px_9px_-4px_rgba(51,45,45,0.2),0_4px_18px_0_rgba(51,45,45,0.1)] focus:bg-neutral-800 focus:shadow-[0_8px_9px_-4px_rgba(51,45,45,0.2),0_4px_18px_0_rgba(51,45,45,0.1)] focus:outline-none focus:ring-0 active:bg-neutral-900 active:shadow-[0_8px_9px_-4px_rgba(51,45,45,0.2),0_4px_18px_0_rgba(51,45,45,0.1)] dark:bg-neutral-900 dark:shadow-[0_4px_9px_-4px_#030202] dark:hover:bg-neutral-900 dark:hover:shadow-[0_8px_9px_-4px_rgba(3,2,2,0.3),0_4px_18px_0_rgba(3,2,2,0.2)] dark:focus:bg-neutral-900 dark:focus:shadow-[0_8px_9px_-4px_rgba(3,2,2,0.3),0_4px_18px_0_rgba(3,2,2,0.2)] dark:active:bg-neutral-900 dark:active:shadow-[0_8px_9px_-4px_rgba(3,2,2,0.3),0_4px_18px_0_rgba(3,2,2,0.2)]">
          <%= link_to 'login', new_user_session_path%>
        </button>
        <% if user_signed_in? %>
          <%= link_to 'logout', destroy_user_session_path, method: :delete %>
        <% end %>
      </div>
      </nav>
    </header>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<%= link_to "新規投稿", new_path %>
<%= link_to "投稿一覧", posts_path%>

app/views/posts/index.html.erb
<%= link_to "新規投稿", new_path %>
<%= link_to "投稿一覧", posts_path%>
<div class="max-w-screen-sm border-solid border-2 border-black ">
    <% @posts.each do |post| %>
        <div>
            <div><%= link_to(post.content, post) %></div>
        </div>
    <% end %>
</div>

app/views/posts/new.html.erb
<%= form_with model: @post, url: posts_create_path do |form| %>
  <%= label_tag(:content, "Content") %>
  <%= text_field_tag(:content) %>
  <%= submit_tag("投稿") %>
<% end %>

app/views/posts/show.html.erb
<h2>詳細</h2>
<%= @post.content %>
<%= @post.created_at %>
<%= link_to '削除', post_path(@post), data: { turbo_method: :delete }%>